# Generated by Django 4.2 on 2024-08-09 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_customersupportticket_and_more'),
        ('Delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='orders',
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='orders',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='Customer.order', verbose_name='order'),
            preserve_default=False,
        ),
    ]
