# Generated by Django 4.2 on 2024-08-14 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth', '0003_user_device_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WareHouseNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.warehouse', verbose_name='warehouse')),
            ],
            options={
                'verbose_name': 'WareHouse Notification',
                'verbose_name_plural': 'WareHouse Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User Notification',
                'verbose_name_plural': 'User Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.driver', verbose_name='driver')),
            ],
            options={
                'verbose_name': 'Driver Notification',
                'verbose_name_plural': 'Driver Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.customer', verbose_name='customer')),
            ],
            options={
                'verbose_name': 'Customer Notification',
                'verbose_name_plural': 'Customer Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
