# Generated by Django 4.2 on 2024-08-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customernotification',
            name='data',
            field=models.JSONField(blank=True, null=True, verbose_name='data'),
        ),
        migrations.AddField(
            model_name='customernotification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notification/images', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='drivernotification',
            name='data',
            field=models.JSONField(blank=True, null=True, verbose_name='data'),
        ),
        migrations.AddField(
            model_name='drivernotification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notification/images', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='data',
            field=models.JSONField(blank=True, null=True, verbose_name='data'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notification/images', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='warehousenotification',
            name='data',
            field=models.JSONField(blank=True, null=True, verbose_name='data'),
        ),
        migrations.AddField(
            model_name='warehousenotification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notification/images', verbose_name='image'),
        ),
    ]
