# Generated by Django 4.2 on 2024-08-03 11:13

import Master.image_uploader
import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import functools
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth', '0002_remove_warehouse_document_and_more'),
        ('General', '0003_alter_country_code_alter_country_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='category title')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=functools.partial(Master.image_uploader.image_rename, *(), **{'path': 'category/image'}), verbose_name='category image')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='title', unique=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.warehouse', verbose_name='warehouse')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='PackagingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('type', models.CharField(max_length=50, verbose_name='Packaging Type')),
            ],
            options={
                'verbose_name': 'Packaging Type',
                'verbose_name_plural': 'Packaging Type',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='rate')),
            ],
            options={
                'verbose_name': 'Tax',
                'verbose_name_plural': 'Taxes',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('name', models.CharField(help_text='Enter units - kilogram, gram etc.', max_length=20, unique=True, verbose_name='name')),
                ('abbreviation', models.CharField(help_text='Enter abbreviation - kg, g etc.', max_length=10, unique=True, verbose_name='abbreviation')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='subcategory title')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=functools.partial(Master.image_uploader.image_rename, *(), **{'path': 'subcategory/image'}), verbose_name='subcategory image')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='title', unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Warehouse.category', verbose_name='category')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.warehouse', verbose_name='warehouse')),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='meta title')),
                ('meta_keyword', models.TextField(blank=True, null=True, verbose_name='meta keywords')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta description')),
                ('canonical', models.URLField(blank=True, null=True, verbose_name='canonical link')),
                ('sku_no', models.CharField(max_length=20, unique=True, verbose_name='sku no.')),
                ('title', models.CharField(max_length=100, verbose_name='product title')),
                ('size', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='size')),
                ('image1', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='product/images', verbose_name='Image 1')),
                ('image2', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='product/images', verbose_name='Image 2')),
                ('image3', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='product/images', verbose_name='Image 3')),
                ('image4', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='product/images', verbose_name='Image 4')),
                ('image5', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='product/images', verbose_name='Image 5')),
                ('attribute_key1', models.CharField(blank=True, max_length=100, null=True, verbose_name='attribute key 1')),
                ('attribute_value1', django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=100, null=True, verbose_name='attribute value 1')),
                ('attribute_key2', models.CharField(blank=True, max_length=100, null=True, verbose_name='attribute key 2')),
                ('attribute_value2', django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=100, null=True, verbose_name='attribute value 2')),
                ('attribute_key3', models.CharField(blank=True, max_length=100, null=True, verbose_name='attribute key 3')),
                ('attribute_value3', django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=100, null=True, verbose_name='attribute value 3')),
                ('attribute_key4', models.CharField(blank=True, max_length=100, null=True, verbose_name='attribute key 4')),
                ('attribute_value4', django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=100, null=True, verbose_name='attribute value 4')),
                ('attribute_key5', models.CharField(blank=True, max_length=100, null=True, verbose_name='attribute key 5')),
                ('attribute_value5', django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=100, null=True, verbose_name='attribute value 5')),
                ('attribute_key6', models.CharField(blank=True, max_length=100, null=True, verbose_name='attribute key 6')),
                ('attribute_value6', django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=100, null=True, verbose_name='attribute value 6')),
                ('attribute_key7', models.CharField(blank=True, max_length=100, null=True, verbose_name='attribute key 7')),
                ('attribute_value7', django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=100, null=True, verbose_name='attribute value 7')),
                ('attribute_key8', models.CharField(blank=True, max_length=100, null=True, verbose_name='attribute key 8')),
                ('attribute_value8', django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=100, null=True, verbose_name='attribute value 8')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(help_text='Enter Detailed Description of Product', verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='price')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='discount %')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='stock quantity')),
                ('reorder_level', models.IntegerField(default=0, verbose_name='reorder level')),
                ('is_available', models.BooleanField(default=True, verbose_name='product available')),
                ('is_active', models.BooleanField(default=True, verbose_name='product active')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='title', unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Warehouse.category', verbose_name='category')),
                ('cgst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cgst_tax', to='Warehouse.tax', verbose_name='CGST')),
                ('country_origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='General.country', verbose_name='country of origin')),
                ('packaging_type', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='Warehouse.packagingtype')),
                ('sgst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sgst_tax', to='Warehouse.tax', verbose_name='SGST')),
                ('size_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Warehouse.unit', verbose_name='size unit')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Warehouse.subcategory', verbose_name='subcategory')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.warehouse', verbose_name='warehouse')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
