# Generated by Django 4.2 on 2024-08-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is deleted'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is deleted'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is deleted'),
        ),
    ]
