# Generated by Django 4.2 on 2024-08-07 10:06

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_unit',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Warehouse.unit', verbose_name='stock unit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='attribute_value1',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='attribute value 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='attribute_value2',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='attribute value 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='attribute_value3',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='attribute value 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='attribute_value4',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='attribute value 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='attribute_value5',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='attribute value 5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='attribute_value6',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='attribute value 6'),
        ),
        migrations.AlterField(
            model_name='product',
            name='attribute_value7',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='attribute value 7'),
        ),
        migrations.AlterField(
            model_name='product',
            name='attribute_value8',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='attribute value 8'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Enter Detailed Description of Product', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='position',
            field=models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right'), ('C', 'Center')], default='C', max_length=8, null=True, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(max_length=50, verbose_name='subcategory title'),
        ),
    ]
