# Generated by Django 4.2 on 2024-08-09 12:31

import Master.token_genrator
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Auth', '0002_driver_latitude_driver_longitude_and_more'),
        ('Warehouse', '0002_product_stock_unit_alter_product_attribute_value1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WareHouseSupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20, verbose_name='status')),
                ('token', models.CharField(default=Master.token_genrator.generate_token, max_length=10, unique=True, verbose_name='token')),
                ('close_date', models.DateTimeField(blank=True, null=True, verbose_name='close date')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.warehouse', verbose_name='warehouse')),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
            },
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Slider', 'verbose_name_plural': 'Sliders'},
        ),
        migrations.RemoveField(
            model_name='slider',
            name='device',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='position',
        ),
        migrations.AddField(
            model_name='product',
            name='exp_date',
            field=models.DateField(blank=True, null=True, verbose_name='expiry date'),
        ),
        migrations.CreateModel(
            name='WareHouseSupportTicketResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('response_text', models.TextField()),
                ('responder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Warehouse.warehousesupportticket')),
            ],
            options={
                'verbose_name': 'Support Ticket Response',
                'verbose_name_plural': 'Support Ticket Responses',
            },
        ),
    ]
