# Generated by Django 4.2 on 2024-08-05 05:45

import Master.myvalidator
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='meta title')),
                ('meta_keyword', models.TextField(blank=True, null=True, verbose_name='meta keywords')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta description')),
                ('canonical', models.URLField(blank=True, null=True, verbose_name='canonical link')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='description')),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('name', models.CharField(max_length=200, verbose_name='full name')),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('mobile', models.CharField(max_length=15, verbose_name='mobile number')),
                ('subject', models.CharField(max_length=200, verbose_name='subject')),
                ('message', models.TextField(verbose_name='message')),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='country')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='country code')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='category title')),
            ],
            options={
                'verbose_name': 'FAQ Category',
                'verbose_name_plural': 'FAQ Categories',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('name', models.CharField(max_length=200, verbose_name='full name')),
                ('message', models.TextField(blank=True, null=True, verbose_name='message')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='rating')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='meta title')),
                ('meta_keyword', models.TextField(blank=True, null=True, verbose_name='meta keywords')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta description')),
                ('canonical', models.URLField(blank=True, null=True, verbose_name='canonical link')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='description')),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policies',
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='meta title')),
                ('meta_keyword', models.TextField(blank=True, null=True, verbose_name='meta keywords')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta description')),
                ('canonical', models.URLField(blank=True, null=True, verbose_name='canonical link')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('favicon', models.ImageField(upload_to='core/siteconfig/favicon/', verbose_name='favicon')),
                ('logo', imagekit.models.fields.ProcessedImageField(upload_to='core/siteconfig/logo/', verbose_name='logo')),
                ('primary_mobile', models.CharField(help_text='Alphabets and special characters are not allowed.', max_length=13, validators=[Master.myvalidator.mobile_validator], verbose_name='primary mobile number')),
                ('secondary_mobile', models.CharField(blank=True, help_text='Alphabets and special characters are not allowed.', max_length=13, null=True, validators=[Master.myvalidator.mobile_validator], verbose_name='secondary mobile number')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='short description')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('playstore', models.URLField(blank=True, null=True, verbose_name='playstore app url')),
                ('appstore', models.URLField(blank=True, null=True, verbose_name='appstore app url')),
            ],
            options={
                'verbose_name': 'Site Config',
                'verbose_name_plural': 'Site Config',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='state name')),
                ('code', models.CharField(max_length=200, unique=True, verbose_name='state code')),
                ('is_available', models.BooleanField(default=True, verbose_name='is available')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='TermsAndCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='meta title')),
                ('meta_keyword', models.TextField(blank=True, null=True, verbose_name='meta keywords')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta description')),
                ('canonical', models.URLField(blank=True, null=True, verbose_name='canonical link')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='description')),
            ],
            options={
                'verbose_name': 'Terms & Conditions',
                'verbose_name_plural': 'Terms & Conditions',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('name', models.CharField(choices=[('whatsapp', 'Whatsapp'), ('linkedin', 'Linkedin'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('threads', 'Threads'), ('x', 'X'), ('youtube', 'Youtube'), ('playstore', 'Playstore'), ('appstore', 'Appstore')], max_length=20, unique=True, verbose_name='platform')),
                ('url', models.URLField(verbose_name='URL')),
                ('site_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='General.siteconfig')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='meta title')),
                ('meta_keyword', models.TextField(blank=True, null=True, verbose_name='meta keywords')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta description')),
                ('canonical', models.URLField(blank=True, null=True, verbose_name='canonical link')),
                ('question', models.CharField(max_length=250, verbose_name='question')),
                ('answer', django_ckeditor_5.fields.CKEditor5Field(verbose_name='answer')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='General.faqcategory')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('name', models.CharField(max_length=200, verbose_name='city name')),
                ('is_available', models.BooleanField(default=True, verbose_name='is available')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='General.state', verbose_name='state')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
    ]
