# Generated by Django 4.2 on 2024-08-07 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='site_config',
        ),
    ]
