# Generated by Django 4.2 on 2024-08-03 07:44

import Master.myvalidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='primary_mobile',
            field=models.CharField(help_text='Alphabets and special characters are not allowed.', max_length=13, validators=[Master.myvalidator.mobile_validator], verbose_name='primary mobile number'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='secondary_mobile',
            field=models.CharField(blank=True, help_text='Alphabets and special characters are not allowed.', max_length=13, null=True, validators=[Master.myvalidator.mobile_validator], verbose_name='secondary mobile number'),
        ),
    ]
