# Generated by Django 4.2 on 2024-08-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0002_alter_siteconfig_primary_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='country code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='state',
            name='code',
            field=models.CharField(max_length=200, unique=True, verbose_name='state code'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='state name'),
        ),
    ]
