# Generated by Django 4.2 on 2024-08-09 12:31

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=12, verbose_name='latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=12, verbose_name='longitude'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_image',
            field=imagekit.models.fields.ProcessedImageField(help_text='Upload warehouse image.', upload_to='auth/warehouse/images', verbose_name='shop image'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_image_owner',
            field=imagekit.models.fields.ProcessedImageField(help_text='Upload warehouse image with owner.', upload_to='auth/warehouse/owner', verbose_name='shop image with owner'),
        ),
    ]
