# Generated by Django 4.2 on 2024-08-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='latitude',
            field=models.DecimalField(decimal_places=9, max_digits=12, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='longitude',
            field=models.DecimalField(decimal_places=9, max_digits=12, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_no',
            field=models.CharField(max_length=15, unique=True, verbose_name='warehouse number'),
        ),
    ]
