# Generated by Django 4.2 on 2024-08-03 07:44

import Master.myvalidator
import django.core.validators
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='document',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='identity_document',
            field=models.FileField(default=True, help_text='Upload Identity Document.', upload_to='auth/warehouse/identity', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='identity document'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='Alphabets and special characters are not allowed (eg.+911234567890).', max_length=13, unique=True, validators=[Master.myvalidator.mobile_validator], verbose_name='mobile number'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='license',
            field=models.FileField(help_text='Upload license proof.', upload_to='auth/warehouse/license', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='license proof'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_image',
            field=imagekit.models.fields.ProcessedImageField(default=True, help_text='Upload warehouse image.', upload_to='auth/warehouse/', verbose_name='shop image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_image_owner',
            field=imagekit.models.fields.ProcessedImageField(default=True, help_text='Upload warehouse image with owner.', upload_to='auth/warehouse/owner/', verbose_name='shop image with owner'),
            preserve_default=False,
        ),
    ]
