# Generated by Django 4.2 on 2024-08-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_driver_latitude_driver_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Device Token'),
        ),
    ]
